apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service-green
spec:
  replicas: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: frontend-service
      version: green
  template:
    metadata:
      labels:
        app: frontend-service
        version: green
    spec:
      containers:
        - name: frontend-service
          image: cesarnunezh/frontend-service:latest
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: frontend-runtime-config
              mountPath: /usr/share/nginx/html/runtime-config.js
              subPath: runtime-config.js
      volumes:
        - name: frontend-runtime-config
          configMap:
            name: app-config
            items:
              - key: runtime-config.js
                path: runtime-config.js
