apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api-blue
spec:
  replicas: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: products-api
      version: blue
  template:
    metadata:
      labels:
        app: products-api
        version: blue
    spec:
      containers:
        - name: products-api
          image: cesarnunezh/products-api:latest
          ports:
            - containerPort: 8070
              name: http
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_ENV
            - name: DEV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DEV
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
