resources:
  - namespace.yaml
  - resourcequota.yaml
  - persistentvolume.yaml
  - ingress.yaml
  - ../../base

namespace: devops-staging

patches:
  - path: deployment-patch.yaml
  - path: service-nodeport-patch.yaml

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - APP_ENV=staging
      - DEV=false
      - REACT_APP_API_ORDERS=/orders
      - REACT_APP_API_PRODUCTS=/products
    files:
      - runtime-config.js=runtime-config.js

generatorOptions:
  disableNameSuffixHash: true
