apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv-staging
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /home/canun/projects/DevOpsProject/k8s/storage/staging/postgres
    type: DirectoryOrCreate
  claimRef:
    namespace: devops-staging
    name: database-pvc
